export const allCountries = [
  { name: "United Arab Emirates", code: "AE" },
  { name: "Argentina", code: "AR" },
  { name: "Austria", code: "AT" },
  { name: "Australia", code: "AU" },
  { name: "Belgium", code: "BE" },
  { name: "Bulgaria", code: "BG" },
  { name: "Brazil", code: "BR" },
  { name: "Canada", code: "CA" },
  { name: "Switzerland", code: "CH" },
  { name: "China", code: "CN" },
  { name: "Colombia", code: "CO" },
  { name: "Cuba", code: "CU" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Germany", code: "DE" },
  { name: "Egypt", code: "EG" },
  { name: "France", code: "FR" },
  { name: "United Kingdom", code: "GB" },
  { name: "Greece", code: "GR" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Indonesia", code: "ID" },
  { name: "Ireland", code: "IE" },
  { name: "Israel", code: "IL" },
  { name: "India", code: "IN" },
  { name: "Italy", code: "IT" },
  { name: "Japan", code: "JP" },
  { name: "South Korea", code: "KR" },
  { name: "Lithuania", code: "LT" },
  { name: "Latvia", code: "LV" },
  { name: "Morocco", code: "MA" },
  { name: "Mexico", code: "MX" },
  { name: "Malaysia", code: "MY" },
  { name: "Nigeria", code: "NG" },
  { name: "Netherlands", code: "NL" },
  { name: "Norway", code: "NO" },
  { name: "New Zealand", code: "NZ" },
  { name: "Philippines", code: "PH" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Romania", code: "RO" },
  { name: "Serbia", code: "RS" },
  { name: "Russia", code: "RU" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Sweden", code: "SE" },
  { name: "Singapore", code: "SG" },
  { name: "Slovenia", code: "SI" },
  { name: "Slovakia", code: "SK" },
  { name: "Thailand", code: "TH" },
  { name: "Turkey", code: "TR" },
  { name: "Taiwan", code: "TW" },
  { name: "Ukraine", code: "UA" },
  { name: "United States", code: "US" },
  { name: "Venezuela", code: "VE" },
  { name: "South Africa", code: "ZA" },
] as const;
